name: Release
on:
  push:
#  pull_request:
#    branches:
#      - '**'
  workflow_dispatch:

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
jobs:
#  test:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        go: ['1.17', '1.18', '1.19']
#    name: Go ${{ matrix.go }} test
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup go
#        uses: actions/setup-go@v3
#        with:
#          go-version: ${{ matrix.go }}
#      - run: go test -race -v -coverprofile=profile.cov ./pkg/...
#      - uses: codecov/codecov-action@v3.1.1
#        with:
#          file: ./profile.cov
#          name: codecov-go
  release:
    name: semantic-release
    runs-on: ubuntu-22.04
#    needs: [test]
#    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new_release_published }}
      new-release-version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Source checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5

  goreleaser:
    name: binary-release
    runs-on: ubuntu-latest
    needs:
      - release
    if: needs.release.outputs.new-release-published == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}